### ISSUE TITLE
FR: Support multiple date formats.

### ISSUE THREAD

**Issue by real-yfprojects** [rioj7/vscode-file-templates#1]
Since I am creating a doc string for each file containing the exact time in one line and the current year in another line, it would be great if `${dateTimeFormat}` would support a parameter called `identifier` to identify a dateTimeFormat definition in settings.json.

The attribute `templates.dateTimeFormat` could be structured like this:

```json
"templates.dateTimeFormat": {
    "identifier1": { definition },
    "identifier2": { definition }
}
```

This would be a great feature to have.

**Comment by rioj7** [comment]
@real-yfprojects  Try v1.1.0

**Comment by real-yfprojects** [comment]
@rioj7 Very nice implementation! Thank you.
