### ISSUE TITLE
Command newFileFromTemplate with pre-defined template variable without user input

### ISSUE THREAD

**Issue by gribok** [rioj7/vscode-file-templates#12]
I would like to define a keybinding that directly execute the command `templates.newFileFromTemplate` with a pre-defined template name.
That user input can be bypassed by passing an arg.

I had following idea for `keybindings.json`.  
The variable`templateName` should be searched in pre-defined `templates.folder`.

``` json
[
    {
        "key": "alt+m",
        "command": "templates.newFileFromTemplate",
        "args": {
            "templateName": "myCustomizedTemplate.txt"
        }
    },
]
```

So: Search for `myCustomizedTemplate.txt` in `templates.folder`.

Do you have any idea how to do that?

**Comment by rioj7** [comment]
@gribok try v1.14.0

**Comment by gribok** [comment]
It works.   
Thank you
