### ISSUE TITLE
Check, if pre-defined file exists as when condition

### ISSUE THREAD

**Issue by gribok** [rioj7/vscode-file-templates#13]
I would like to check, if `fileExists` (boolean) based on calculated filename by template, related to #12, 
As an idea is to define a `when` condition ([link](https://code.visualstudio.com/api/references/when-clause-contexts#add-a-custom-when-clause-context)) with `setContext `in the extension.
This condition would avoid throwing the error `File already exists.`
Then the command can be executed as part of a chain of commands (e.g. `runCommands` in `keybindings.json`), even if file already exists.

An example:
``` json
{
    "key": "alt+m",
    "command": "templates.newFileFromTemplate",
    "args": { "templateName": "myCustomizedTemplate.html" },
    "when": "!templates.fileExists"
  }
```

Thank you for implementing #10

**Comment by rioj7** [comment]
@gribok try v1.14.1

```json
  {
    "key": "alt+m",
    "command": "templates.newFileFromTemplate",
    "args": {
      "templateName": "myCustomizedTemplate.html",
      "fileExists": "silent"
    }
  }
```

or try:

`"fileExists": "open"`

**Comment by gribok** [comment]
It works like a charm.   
Thank you.
