### ISSUE TITLE
Cannot read properties of undefined (reading 'toDateString')

### ISSUE THREAD

**Issue by cantabria** [rioj7/vscode-file-templates#14]
Hi,
suddently this evening your extension has stop to work reporting the uncaught error: Cannot read properties of undefined (reading 'toDateString').

The template is very simple:
```none
/******************************************
 *  Author : ${author}
 *  Created On : ${dateTimeFormat}
 *  File : ${fileBasename}
 ******************************************/
```
The error still exists even if I remove the CreatedOn line from template.
Reinstalling the extension (v.1.15.0) did'nt resolve the error.
Do you have any idea ?

Thank you
christian

**Comment by rioj7** [comment]
@cantabria  please try v1.15.1 - fixed in 2669c73

I had fallen in the async trap. It happens after the current function terminates.

Even if you are "convinced" that the change should work you should test it.
