### ISSUE TITLE
Created File is not saved after filling input variables.

### ISSUE THREAD

**Issue by real-yfprojects** [rioj7/vscode-file-templates#2]
When using `${input:prompt:}` the file is created, then a popup is shown asking for the input. After hitting enter the input is inserted into the file. But the file is not saved.

It would be really great if the file was saved after inserting the input variables.

**Comment by rioj7** [comment]
@real-yfprojects In v1.3.0 I have added the setting: `templates.saveAfterInputVariableOnFileCreation`

**Comment by real-yfprojects** [comment]
Thanks @rioj7!

**Comment by rioj7** [comment]
@real-yfprojects In v1.3.0 the input variable now has a named version and find/replace to modify/copy the entered text on a different place in the file.

In v1.4.0 the snippet variable now supports `noUI` to expand the variable transform snippets on file creation, these type of snippets don't need **Snippet** mode of the editor.

If there was a way to notify the users of [File Templates](https://marketplace.visualstudio.com/items?itemName=bam.vscode-file-templates) by Venkatesh Boddu that there is an update/fix/fork of that extension, namely this. It looks like Venkatesh hasn't updated/fixed for 4 years.

**Comment by real-yfprojects** [comment]
> If there was a way to notify the users of [File Templates](https://marketplace.visualstudio.com/items?itemName=bam.vscode-file-templates) by Venkatesh Boddu that there is an update/fix/fork of that extension, namely this.

I don't think there is a way since the author of Boddu didn't provide any links to a repo or something like that. The users will have to figure it out by themselves. If one searches for `File Templates` on the marketplace, there are several alternatives including yours listed.
