### ISSUE TITLE
File naming behaviour results in double file ending.

### ISSUE THREAD

**Issue by real-yfprojects** [rioj7/vscode-file-templates#3]
When creating a new file the user is asked for a file name. I often type in the full file name including the file ending. The file ending  for the file created is appended any ways. This results in a doubled file ending. E.g. `test.py.py`. Instead the extension should detect that the file types file ending is already specified and don't append it again.

**Comment by rioj7** [comment]
@real-yfprojects it was behavior similar to original extension. Fixed in version 1.1.1

**Comment by real-yfprojects** [comment]
> Fixed in version 1.1.1

Thanks, @rioj7!
