### ISSUE TITLE
Transform (find/replace) variables

### ISSUE THREAD

**Issue by cis-jamie** [rioj7/vscode-file-templates#6]
Are you able to add a namespace vibrable?

This could be worked out using ${relativeFileDirname}

e.g. ${relativeFileDirname} = src/App/UserBundle/Form

to be transformed into:
${namespace} = App\UserBundle\Form

Removing src/ and swapping the forward slashes to backward slashes?

Or is there any other way that could be achieved? e.g. using any functions within your extension, to manipulate variables? e.g. a string replace function

**Comment by cis-jamie** [comment]
@rioj7 that's true, being able to edit it with regex or using replaceAll like e.g. ${ relativeFileDirname.replaceAll('src/', '').replaceAll('/', '\\') } would be able to achieve the ability to create namespaces with flexibility. This would be the best approach, then it can be used for anything else, if required.

**Comment by rioj7** [comment]
@cis-jamie Have a try with v1.6.0 and the variable definition

```
${relativeFileDirname#find=^src/#replace=#find=/#replace=\\#}
```
