### ISSUE TITLE
date as filename

### ISSUE THREAD

**Issue by mtuckerb** [rioj7/vscode-file-templates#7]
I am struggling to create a template that uses the current date (formatted) as the filename. I am trying to recreate vimwiki style functionality, and this is the big missing piece. currently I have:

```javascript
##@@## ~/vimwiki/diary/${ templates.dateTimeFormat: { "locale": "en-US", "options": { "year": "2-digit", "month": "2-digit", "day": "2-digit", }, "template": "${year}-${month}-${day}" } 
---
title:  ${templates.dateTimeFormat: {
        "locale": "en-US",
        "options": {
           "year": "numeric",
           "month": "long",
           "day": "long",
           "weekday": "long"
        },
        "template": "${weekday}  ${month} ${day}  ${year}"
    }
}
#  ${templates.dateTimeFormat: {
        "locale": "en-US",
        "options": {
           "year": "numeric",
           "month": "long",
           "day": "long",
           "weekday": "long"
        },
        "template": "${weekday} ${month} ${day}  ${year}",
    }
}
author: ${author}
---

```

**Comment by mtuckerb** [comment]
perfect. Relative path (from the .vs-code/templates) worked well for me. I had _just_ figured out that it belonged in settings, and then had to figure out how to open the settings.json file :) thanks so much for your help!

**Comment by rioj7** [comment]
@mtuckerb Have a look at the new `${dateTimeFormat}` possibilities to pass the properties

**Comment by mtuckerb** [comment]
very nice! Thank you!

**Comment by rioj7** [comment]
@mtuckerb Have a look at v1.9.0: absolute and relative placement of files with `##@@##`

**Comment by mtuckerb** [comment]
AWESOME! Thank you!!
